spring:
  datasource:
    url: jdbc:h2:mem:tradedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
#Financial websocket
financial:
  twelve:
    api:
      token: ${TWELVE_API_KEY:twelve}
  websocket:
    url: wss://ws.finnhub.io  # Replace with actual WebSocket URL
  api:
    token: ${FINANCIAL_API_TOKEN:test}
# Redis config
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8081

redis:
  default-retention: 3600000